FROM hypriot/rpi-node:8

RUN [ "cross-build-start" ]

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN apt-get update && \
        apt-get install -y --no-install-recommends \
        avahi-daemon \
        avahi-discover \
        build-essential \
        iputils-ping \
        libavahi-compat-libdnssd-dev \
        libnss-mdns && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /var/run/dbus

RUN npm config set unsafe-perm true
	
RUN npm install -g homebridge --unsafe-perm

RUN npm install -g homebridge-mqtt --unsafe-perm

# MISC settings
#COPY wle-homebridge/avahi-daemon.conf /etc/avahi/avahi-daemon.conf

USER root

RUN mkdir -p /root/.homebridge

ADD wle-homebridge/run.sh /root/run.sh

ADD wle-homebridge/config.json /root/.homebridge/config.json

RUN chmod +x /root/run.sh

# Run container
EXPOSE 5353 51826
CMD ["/root/run.sh"]
#CMD ["homebridge"]
