FROM agileiot/agile-core-armv7l:v0.2.3

COPY wle-agile-core/protocol-manager-1.0-jar-with-dependencies.jar iot.agile.ProtocolManager/target/protocol-manager-1.0-jar-with-dependencies.jar
COPY wle-agile-core/device-manager-1.0-jar-with-dependencies.jar iot.agile.DeviceManager/target/device-manager-1.0-jar-with-dependencies.jar
COPY wle-agile-core/DeviceFactory-1.0-jar-with-dependencies.jar iot.agile.DeviceFactory/target/DeviceFactory-1.0-jar-with-dependencies.jar
COPY wle-agile-core/http-1.0-jar-with-dependencies.jar iot.agile.http/target/http-1.0-jar-with-dependencies.jar

COPY wle-agile-core/iot/agile/device/instance iot.agile.DeviceFactory/target/classes/iot/agile/device/instance
COPY wle-agile-core/iot/agile/device/instance iot.agile.DeviceFactory/target/iot/agile/device/instance

CMD [ "bash", "/usr/src/app/scripts/start.sh" ]